declare module '@mui/material/styles' {
    interface Palette {
        primaryColor25: { main: string }
        primaryColor50: { main: string }
        primaryColor100: { main: string }
        primaryColor200: { main: string }
        primaryColor300: { main: string }
        primaryColor400: { main: string }
        primaryColor500: { main: string }
        primaryColor600: { main: string }
        primaryColor700: { main: string }
        primaryColor800: { main: string }
        primaryColor900: { main: string }
        secondaryColor25: { main: string }
        secondaryColor50: { main: string }
        secondaryColor100: { main: string }
        secondaryColor200: { main: string }
        secondaryColor300: { main: string }
        secondaryColor400: { main: string }
        secondaryColor500: { main: string }
        secondaryColor600: { main: string }
        secondaryColor700: { main: string }
        secondaryColor800: { main: string }
        secondaryColor900: { main: string }
        errorColor25: { main: string }
        errorColor50: { main: string }
        errorColor100: { main: string }
        errorColor200: { main: string }
        errorColor300: { main: string }
        errorColor400: { main: string }
        errorColor500: { main: string }
        errorColor600: { main: string }
        errorColor700: { main: string }
        errorColor800: { main: string }
        errorColor900: { main: string }
        successColor25: { main: string }
        successColor50: { main: string }
        successColor100: { main: string }
        successColor200: { main: string }
        successColor300: { main: string }
        successColor400: { main: string }
        successColor500: { main: string }
        successColor600: { main: string }
        successColor700: { main: string }
        successColor800: { main: string }
        successColor900: { main: string }
        warningColor25: { main: string }
        warningColor50: { main: string }
        warningColor100: { main: string }
        warningColor200: { main: string }
        warningColor300: { main: string }
        warningColor400: { main: string }
        warningColor500: { main: string }
        warningColor600: { main: string }
        warningColor700: { main: string }
        warningColor800: { main: string }
        warningColor900: { main: string }
    }
    interface PaletteOptions {
        primaryColor25?: { main: string }
        primaryColor50?: { main: string }
        primaryColor100?: { main: string }
        primaryColor200?: { main: string }
        primaryColor300?: { main: string }
        primaryColor400?: { main: string }
        primaryColor500?: { main: string }
        primaryColor600?: { main: string }
        primaryColor700?: { main: string }
        primaryColor800?: { main: string }
        primaryColor900?: { main: string }
        secondaryColor25?: { main: string }
        secondaryColor50?: { main: string }
        secondaryColor100?: { main: string }
        secondaryColor200?: { main: string }
        secondaryColor300?: { main: string }
        secondaryColor400?: { main: string }
        secondaryColor500?: { main: string }
        secondaryColor600?: { main: string }
        secondaryColor700?: { main: string }
        secondaryColor800?: { main: string }
        secondaryColor900?: { main: string }
        errorColor25?: { main: string }
        errorColor50?: { main: string }
        errorColor100?: { main: string }
        errorColor200?: { main: string }
        errorColor300?: { main: string }
        errorColor400?: { main: string }
        errorColor500?: { main: string }
        errorColor600?: { main: string }
        errorColor700?: { main: string }
        errorColor800?: { main: string }
        errorColor900?: { main: string }
        successColor25?: { main: string }
        successColor50?: { main: string }
        successColor100?: { main: string }
        successColor200?: { main: string }
        successColor300?: { main: string }
        successColor400?: { main: string }
        successColor500?: { main: string }
        successColor600?: { main: string }
        successColor700?: { main: string }
        successColor800?: { main: string }
        successColor900?: { main: string }
        warningColor25?: { main: string }
        warningColor50?: { main: string }
        warningColor100?: { main: string }
        warningColor200?: { main: string }
        warningColor300?: { main: string }
        warningColor400?: { main: string }
        warningColor500?: { main: string }
        warningColor600?: { main: string }
        warningColor700?: { main: string }
        warningColor800?: { main: string }
        warningColor900?: { main: string }
    }
}

export {}
